### ISSUE TITLE
Нужна схема базы

### ISSUE THREAD

**Issue by fey** [aeifn/math.ru#2]
Необходимо приложить схему или дамп базы, так как приложение при запуске загружает новости из таблицы `news`, а в репо этого всего нет.

**Comment by aeifn** [comment]
https://math.ru/~egor/math.sql

**Comment by aeifn** [comment]
Рабочий дамп: https://www.dropbox.com/s/rq3mhj1t8hyrmhb/math.sql.zip?dl=0
